#!/bin/bash
# Setup ROCm and PyTorch for AMD GPU (Radeon RX 5500)

echo "=== AMD GPU ROCm + PyTorch Installation Guide ==="
echo ""
echo "NOTE: Radeon RX 5500 (Navi 14) requires ROCm 5.x or 6.x"
echo ""
echo "Run these commands manually with sudo access:"
echo ""
echo "# 1. Install AMD GPU drivers and ROCm"
echo "wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/jammy/amdgpu-install_6.2.60204-1_all.deb"
echo "sudo dpkg -i amdgpu-install_6.2.60204-1_all.deb"
echo "sudo apt-get update"
echo "sudo amdgpu-install --usecase=rocm --no-dkms"
echo ""
echo "# 2. Add user to render and video groups"
echo "sudo usermod -a -G render,video \$USER"
echo ""
echo "# 3. Reboot system"
echo "sudo reboot"
echo ""
echo "# 4. After reboot, verify ROCm installation"
echo "rocm-smi"
echo "rocminfo"
echo ""
echo "# 5. Install PyTorch with ROCm in venv"
echo "cd /home/mnx/bd-traffic-signs"
echo "source venv/bin/activate"
echo "pip uninstall -y torch torchvision torchaudio"
echo "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2"
echo ""
echo "# 6. Verify PyTorch sees AMD GPU"
echo "python -c 'import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name(0))'"
echo ""
echo "=== ALTERNATIVE: Use CPU (Already Working) ==="
echo "Your training is already working on CPU. It's slower but reliable."
echo "Estimated time: ~20 hours for 50 epochs on CPU vs ~3-4 hours on GPU"
